@https = https://localhost:7085

### Test connection
GET {{https}}/api/v1/

### ------------------------------------------
### SOURCE 1:
@source1 = PluginCrawlTruyenFull

### Search
@keyword1 = anh%20dao
@pageS1 = 1
GET {{https}}/api/v1/search?source={{source1}}&keyword={{keyword1}}&page={{pageS1}}

### Novel detail
@novelSlug1 = tao-tac
GET {{https}}/api/v1/novel/{{source1}}/{{novelSlug1}}

### Chapters list
@pageC1 = -1
GET {{https}}/api/v1/novel/{{source1}}/{{novelSlug1}}/chapters?page={{pageC1}}

### Chapter content
@chapSlug1 = chuong-1
GET {{https}}/api/v1/novel/{{source1}}/{{novelSlug1}}/{{chapSlug1}}



### ------------------------------------------
### SOURCE 2:
@source2 = TruyenTangThuVienVn

### Search
@keyword2 = anh%20dao
@pageS2 = 1
GET {{https}}/api/v1/search?source={{source2}}&keyword={{keyword2}}&page={{pageS2}}

### Novel detail
@novelSlug2 = dai-thien-thanh-dao
GET {{https}}/api/v1/novel/{{source2}}/{{novelSlug2}}

### Chapters list
@pageC2 = -1
GET {{https}}/api/v1/novel/{{source2}}/{{novelSlug2}}/chapters?page={{pageC2}}
Accept: application/json

### Chapter content
@chapSlug2 = chuong-1
GET {{https}}/api/v1/novel/{{source2}}/{{novelSlug2}}/{{chapSlug2}}

### ------------------------------------------
### SOURCE 3:
@source3 = TruyenSSVn

### Search
@keyword3 = anh%20dao
@pageS3 = 1
GET {{https}}/api/v1/search?source={{source3}}&keyword={{keyword3}}&page={{pageS3}}

### Novel detail
@novelSlug3 = dai-thien-thanh-dao
GET {{https}}/api/v1/novel/{{source3}}/{{novelSlug3}}

### Chapters list
@pageC3 = -1
GET {{https}}/api/v1/novel/{{source3}}/{{novelSlug3}}/chapters?page={{pageC3}}
Accept: application/json

### Chapter content
@chapSlug3 = chuong-1
GET {{https}}/api/v1/novel/{{source3}}/{{novelSlug3}}/{{chapSlug3}}
