@NovelsCollector.Core_HostAddress = http://localhost:5035

GET {{NovelsCollector.Core_HostAddress}}/api/v1/
Accept: application/json

###

### Search "anh dao"
GET {{NovelsCollector.Core_HostAddress}}/api/v1/search?keyword=anh%20dao
Accept: application/json
